const textosMx = {
  login_page_texto_recuperar_contrasena_1: "Ingresa al siguiente",
  login_page_texto_recuperar_contrasena_2: "enlace",
  login_page_texto_recuperar_contrasena_3: "para recuperar tu contraseña",
  input_usuario: "Usuario",
  input_usuario_descripcion: "Ingrese el usuario",
  input_correo: "Correo",
  input_correo_descripcion: "Ingrese el correo",
  input_contrasena: "Contraseña",
  input_contrasena_descripcion: "Ingrese la contraseña",
  input_validation_requerido: "Requerido",
  login_page_titulo: "Inicio de sesión",
  login_page_ingrese_credenciales: "Ingrese usuario y contraseña",
  login_form_component_acceder: "Acceder",
  input_validation_email_invalido: "Correo inválido",
  login_error: "Error al iniciar sesión",
  menu_home_titulo: "Menú",
  menu_regresar_inicio: "Inicio",
  menu_cerrar_sesion: "Cerrar Sesión",
  http_exito_registrar: "Éxito al registrar",
  http_error_registrar: "Error al registrar",
  input_validation_min_4: "Debe tener más de 4 caracteres",
  input_validation_max_150: "No debe tener más de 150 caracteres",
  input_validation_formato_invalido: "Formato inválido",
  input_validation_min_10_digitos: "Se requieren minimo 10 digitos",
  input_validation_max_10_digitos: "Máximo 10 digitos",
  input_validation_solo_numeros: "Sólo se permiten números",
  input_validation_password_coincidir: "Las contraseñas no coinciden",
  set_general_editar_usuario: "Editar usuario",
  input_telefono: "Teléfono",
  general_desactivar_usuario: "Desactivar usuario",
  general_editar_usuario: "Editar usuario",
  input_nombre: "Nombre",
  usuario_editado_correctamente: "Usuario editado correctamente",
  reactivado_correctamente: "Usuario reactivado correctamente",
  desactivado_correctamente: "Usuario desactivado correctamente",
  input_password: "Contraseña",
  input_password_confirm: "Confirmar contraseña",
  iniciar_sesion: "Iniciar Sesión",
  recupera_password_page_titulo: "Recuperar contraseña",
  recupera_password_ingresa_correo: "Ingresa el correo de tu cuenta",
  recuperacion_contrasena_inicio_proceso_exito:
    "Se envió el link a tu correo para recuperar la contraseña",
  password_recover_validacion_page_titulo: "Actualización de la contraseña",
  input_contrasena_confirmacion: "Confirma contraseña",
  general_actualizar_contra: "Actualizar contraseña",
  recuperacion_contrasena_exito_al_actualizar: "Exito al actualizar la contraseña",
  password_recover_validacion_page_token_invalido: "El token proporcionado es inválido",
  general_reactivar_usuario: "Reactivar usuario",
  sin_proveedores_registrados: "Sin proveedores registrados",
  sin_categorias_registradas: "Sin categorías registradas",
  input_nombre_producto: "Nombre producto",
  input_descripcion: "Descripción",
  input_marca: "Marca",
  input_sku: "SKU",
  input_color: "Color",
  select_proveedores: "Selecciona el proveedor",
  select_categoria_producto: "Selecciona la categoría del producto",
  input_costo_con_iva: "Costo con IVA",
  input_costo_sin_iva: "Costo sin IVA",
  input_costo_puntos_con_iva: "Costo en puntos con IVA",
  input_costo_puntos_sin_iva: "Costo en puntos sin IVA",
  input_fee_brimagy: "Fee Brimagy",
  input_subtotal: "Subtotal",
  input_envio_base: "Envío base",
  input_costo_caja: "Costo caja",
  input_envio_extra: "Envio extra",
  input_total_envio: "Total envío",
  input_total: "Total",
  input_puntos: "Puntos",
  input_factor: "Factor",
  alta_nuevo_producto: "Alta de producto",
  registra_nuevo_producto_catalogo: "Añade un nuevo producto a tu catálogo",
  set_añadir_producto: "Añadir producto",
  general_añadiendo: "Añadiendo",
  set_añadir: "Añadir",
  proveedores: "Proveedores",
  categorias: "Categorías",
  producto_añadido_correctamente: "Producto añadido correctamente",
  general_editar: "Editar",
  general_eliminar: "Eliminar",
  set_general_editar_producto: "Editar producto",
  set_editar_producto: "Editar producto",
  producto_editado_correctamente: "Producto editado correctamente",
  eliminar_producto_confirmar: "¿Deseas eliminar este producto?",
  producto_eliminado_correctamente: "Producto eliminado correctamente",
  producto_eliminado_error: "Error al eliminar el producto",
  eliminar_categoria_confirmar: "¿Deseas eliminar esta categoría?",
  eliminar_proveedor_confirmar: "¿Deseas eliminar este proveedor?",
  set_editar_proveedor: "Editar proveedor",
  set_editar_categoria: "Editar categoría",
  general_eliminado_correctamente: "Eliminado correctamente",
  general_eliminado_error: "Error al eliminar",
  sin_registros: "Sin registros",
  general_editado_correctamente: "Editado correctamente",
  general_editado_error: "Error al editar",
  proveedor_creado_correctamente: "Proveedor creado correctamente",
  proveedor_creado_error: "Error al crear el proveedor",
  categoria_creada_correctamente: "Categoría creada correctamente",
  categoria_creada_error: "Error al crear la categoría",
  input_buscador: "Buscar producto",
  input_email_descripcion: "Ingresa el correo",
  sin_productos_registrados: "Sin productos registrados",
  input_buscar_por_puntos: "Buscar por puntos",
  realizando_busqueda: "Realizando búsqueda",
  realizar_busqueda_magica: "Realizar búsqueda",
  sin_canjes_registrados: "Sin canjes registrados",
  generar_pdf_input: "Generar PDF",
  validar_identidad_input: "Validar identidad del cliente",
  validacion_enviada_correctamente: "Validación enviada correctamente al cliente",
  validacion_enviada_error: "Error al enviar la validación al cliente",
  codigo_enviado_whatsapp_correctamente: "Código enviado correctamente por WhatsApp",
  solicitar_codigo_input: "Solicitar código de verificación",
  identidad_validada_correctamente: "Identidad validada correctamente",
};

export default textosMx;
