const textosMx = {
  login_page_texto_recuperar_contrasena_1: "Ingresa al siguiente",
  login_page_texto_recuperar_contrasena_2: "enlace",
  login_page_texto_recuperar_contrasena_3: "para recuperar tu contraseña",
  input_usuario: "Usuario",
  input_usuario_descripcion: "Ingrese el usuario",
  input_correo: "Correo",
  input_correo_descripcion: "Ingrese el correo",
  input_contrasena: "Contraseña",
  input_contrasena_descripcion: "Ingrese la contraseña",
  input_validation_requerido: "Requerido",
  login_page_titulo: "Inicio de sesión",
  login_page_ingrese_credenciales: "Ingrese usuario y contraseña",
  login_form_component_acceder: "Acceder",
  input_validation_email_invalido: "Correo inválido",
  login_error: "Error al iniciar sesión",
  menu_home_titulo: "Menú",
  menu_regresar_inicio: "Inicio",
  menu_cerrar_sesion: "Cerrar Sesión",
  http_exito_registrar: "Éxito al registrar",
  http_error_registrar: "Error al registrar",
  input_validation_min_4: "Debe tener más de 4 caracteres",
  input_validation_max_150: "No debe tener más de 150 caracteres",
  input_validation_formato_invalido: "Formato inválido",
  input_validation_min_10_digitos: "Se requieren minimo 10 digitos",
  input_validation_max_10_digitos: "Máximo 10 digitos",
  input_validation_solo_numeros: "Sólo se permiten números",
  input_validation_password_coincidir: "Las contraseñas no coinciden",
  set_general_editar_usuario: "Editar usuario",
  input_telefono: "Teléfono",
  general_desactivar_usuario: "Desactivar usuario",
  general_editar_usuario: "Editar usuario",
  input_nombre: "Nombre",
  usuario_editado_correctamente: "Usuario editado correctamente",
  reactivado_correctamente: "Usuario reactivado correctamente",
  desactivado_correctamente: "Usuario desactivado correctamente",
  input_password: "Contraseña",
  input_password_confirm: "Confirmar contraseña",
  iniciar_sesion: "Iniciar Sesión",
  recupera_password_page_titulo: "Recuperar contraseña",
  recupera_password_ingresa_correo: "Ingresa el correo de tu cuenta",
  recuperacion_contrasena_inicio_proceso_exito:
    "Se envió el link a tu correo para recuperar la contraseña",
  password_recover_validacion_page_titulo: "Actualización de la contraseña",
  input_contrasena_confirmacion: "Confirma contraseña",
  general_actualizar_contra: "Actualizar contraseña",
  recuperacion_contrasena_exito_al_actualizar: "Exito al actualizar la contraseña",
  password_recover_validacion_page_token_invalido: "El token proporcionado es inválido",
  general_reactivar_usuario: "Reactivar usuario",
  sin_proveedores_registrados: "Sin proveedores registrados",
  sin_categorias_registradas: "Sin categorías registradas",
  input_nombre_producto: "Nombre producto",
  input_descripcion: "Descripción",
  input_marca: "Marca",
  input_sku: "SKU",
  input_color: "Color",
  input_talla: "Talla",
  select_proveedores: "Selecciona el proveedor",
  select_categoria_producto: "Selecciona la categoría del producto",
  input_costo_con_iva: "Costo proveedor con IVA",
  input_costo_sin_iva: "Costo proveedor sin IVA",
  input_costo_puntos_con_iva: "Costo en puntos con IVA",
  input_costo_puntos_sin_iva: "Costo en puntos sin IVA",
  input_fee_brimagy: "Fee Brimagy",
  input_subtotal: "Subtotal",
  input_envio_base: "Envío base",
  input_costo_caja: "Costo caja",
  input_envio_extra: "Envio extra",
  input_total_envio: "Total envío",
  input_total: "Total",
  input_puntos: "Puntos",
  input_factor: "Factor",
  alta_nuevo_producto: "Alta de producto",
  registra_nuevo_producto_catalogo: "Añade un nuevo producto a tu catálogo",
  set_añadir_producto: "Añadir producto",
  general_añadiendo: "Añadiendo",
  set_añadir: "Añadir",
  proveedores: "Proveedores",
  categorias: "Categorías",
  producto_añadido_correctamente: "Producto añadido correctamente",
  general_editar: "Editar",
  general_eliminar: "Eliminar",
  set_general_editar_producto: "Editar producto",
  set_editar_producto: "Editar producto",
  producto_editado_correctamente: "Producto editado correctamente",
  eliminar_producto_confirmar: "¿Deseas eliminar este producto?",
  producto_eliminado_correctamente: "Producto eliminado correctamente",
  producto_eliminado_error: "Error al eliminar el producto",
  eliminar_categoria_confirmar: "¿Deseas eliminar esta categoría?",
  eliminar_proveedor_confirmar: "¿Deseas eliminar este proveedor?",
  set_editar_proveedor: "Editar proveedor",
  set_editar_categoria: "Editar categoría",
  general_eliminado_correctamente: "Eliminado correctamente",
  general_eliminado_error: "Error al eliminar",
  sin_registros: "Sin registros",
  general_editado_correctamente: "Editado correctamente",
  general_editado_error: "Error al editar",
  proveedor_creado_correctamente: "Proveedor creado correctamente",
  proveedor_creado_error: "Error al crear el proveedor",
  categoria_creada_correctamente: "Categoría creada correctamente",
  categoria_creada_error: "Error al crear la categoría",
  input_buscador: "Buscar producto",
  input_email_descripcion: "Ingresa el correo",
  sin_productos_registrados: "Sin productos registrados",
  sin_productos_digitales_registrados: "Sin productos digitales registrados",
  sin_productos_fisicos_registrados: "Sin productos fisicos registrados",
  input_buscar_por_puntos: "Buscar por puntos",
  realizando_busqueda: "Realizando búsqueda",
  realizar_busqueda_magica: "Realizar búsqueda",
  sin_canjes_registrados: "Sin canjes registrados",
  generar_pdf_input: "Generar PDF",
  validar_identidad_input: "Validar identidad del cliente",
  validacion_enviada_correctamente: "Validación enviada correctamente al cliente",
  validacion_enviada_error: "Error al enviar la validación al cliente",
  codigo_enviado_whatsapp_correctamente: "Código enviado correctamente por WhatsApp",
  solicitar_codigo_input: "Solicitar código de verificación",
  identidad_validada_correctamente: "Identidad validada correctamente",
  input_razon_social: "Razón social",
  input_nombre_contacto: "Nombre del contacto",
  select_tipo_producto: "Selecciona el tipo de producto",
  reenviar_codigo_verificacion: "Reenviar código",
  enviar_a_otro_proveedor: "Enviar a otro proveedor",
  marcar_como_compra_digital: "Marcar como compra digital",
  producto_compra_digital_confirmar: "¿Deseas marcar el producto como una compra digital?",
  enviar_a_proveedor: "Enviar a proveedor",
  generar_orden_compra: "Generar orden de compra",
  exito_enviar_orden_proveedor: "Se ha enviado la cotización al proveedor",
  exito_enviar_cotizacion_proveedor: "Cotización enviada con éxito al proveedor",
  validar_producto: "Aceptar producto",
  rechazar_producto: "Rechazar producto",
  producto_aceptado_correctamente: "Producto aceptado correctamente",
  producto_aceptado_error: "Error al aceptar el producto",
  producto_rechazado_correctamente: "Producto rechazado correctamente",
  producto_rechazado_error: "Error al rechazar el producto",
  enviar_a_aprobacion: "Enviar a aprobación",
  seleccionar_categoria: "Seleccionar categoría",
  input_notas: "Agregar observaciones",
  orden_compra_enviada_aprobacion_exito: "Cotización enviada con éxito para su aprobación",
  ver_detalles: "Ver detalles",
  ver_orden_compra: "Ver orden de compra",
  no_hay_canjes_validados_disponibles: "No hay canjes validados disponibles",
  enviar_orden_de_compra: "Enviar orden de compra a proveedor",
  exito_enviar_orden_compra_proveedor: "La orden de compra fue enviada al proveedor exitosamente",
  error_enviar_orden_compra_proveedor: "Error al enviar la orden de compra al proveedor",
  validar_xml_factura: "Validar XML de la factura",
  factura_validada_correctamente: "Factura validada correctamente",
  factura_validada_error: "Error al validar la factura",
  validar_xml: "Validar",
  subir_pdf_factura: "Subir PDF",
  subir_pdf_factura_placeholder: "Subir PDF de la factura",
  pdf_factura_subido_correctamente: "PDF de la factura subido correctamente",
  pdf_factura_subido_error: "Error al subir el PDF de la factura",
  orden_compra_final_validada_exito: "Orden de compra validada correctamente",
  orden_compra_final_validada_error: "Error al validar la orden de compra",
  validar_orden_de_compra: "Validar orden de compra",
  generar_orden_compra_pdf: "Generar PDF de la orden de compra",
  select_proveedor: "Selecciona el proveedor",
  sin_canjes_validados_registrados: "Sin canjes validados",
  rechazar_cotizacion_proveedor: "Rechazar cotización del proveedor",
  cotizacion_rechazada_correctamente: "Cotización rechazada correctamente",
  cotizacion_rechazada_error: "Error al rechazar la cotización",
  no_hay_proveedores_con_el_producto: "No hay proveedores con el producto",
  exito_enviar_producto_a_otro_proveedor: "Producto enviado a otro proveedor correctamente",
  error_enviar_producto_a_otro_proveedor: "Error al enviar el producto al proveedor",
  recibir_en_almacen: "Recibir en almacen",
  asignar_guia_envio: "Asignar guía de envío",
  enviar_producto: "Enviar producto",
  confirmar_recepcion_producto: "Confirmar recepción del producto",
  input_cantidad_producto: "Cantidad por recibir",
  set_añadir_producto_almacen: "Añadir a almacen",
  exito_recibir_producto: "Éxito al recibir el producto",
  input_guia_producto: "Añadir guía del producto",
  set_añadir_guia_producto_almacen: "Añadir guía del producto",
  guia_añadida_correctamente: "Guía añadida correctamente",
  guia_añadida_error: "Error al añadir la guía",
  producto_enviado_correctamente: "Producto enviado correctamente",
  producto_enviado_error: "Error al enviar el producto",
  producto_entregado_correctamente: "El producto fue entregado correctamente",
  producto_entregado_error: "Error al entregar el producto",
  añadir_evidencia_producto: "Añadir envidencia del producto",
  set_general_evidencia: "Añadir evidencia",
  http_exito_evidencia_enviada: "Evidencia añadida con éxito",
  añadir_fecha_pago_factura_correctamente: "Fecha de pago añadida correctamente",
  añadir_fecha_pago_factura_error: "Error al añadir fecha de pago",
  set_añadir_fecha_pago_factura: "Añadir fecha de pago",
  input_fecha_pago: "Fecha de pago",
  sin_encuestas_registradas: "Sin encuestas registradas",
  pregunta_añadida_correctamente: "Pregunta añadida correctamente",
  pregunta_añadida_error: "Error al añadir la pregunta",
  set_añadir_pregunta: "Añadir pregunta",
  input_pregunta: "Pregunta",
  select_tipo_encuesta: "Tipo de encuesta",
  select_tipo_pregunta: "Tipo de pregunta",
  set_editar_pregunta: "Editar pregunta",
  pregunta_editada_correctamente: "Pregunta editada correctamente",
  pregunta_editada_error: "Error al editar la pregunta",
  pregunta_desactivada_correctamente: "Pregunta desactivada correctamente",
  pregunta_desactivada_error: "Error al desactivar la pregunta",
  pregunta_activada_correctamente: "Pregunta activada correctamente",
  pregunta_activada_error: "Error al activar la pregunta",
  encuesta_enviada_correctamente: "Encuesta enviada correctamente",
  encuesta_enviada_error: "Error al enviar la encuesta",
  set_enviar_encuesta: "Enviar encuesta",
  general_enviando: "Enviando",
  enviar_respuestas: "Enviar respuestas",
  exito_añadir_respuestas: "Respuestas añadidas correctamente",
  error_añadir_respuestas: "Error al añadir las respuestas",
  enviar_encuesta: "Enviar encuesta",
  general_ver_respuesta: "Ver respuestas",
  no_notificaciones_nuevas: "¡No tienes notificaciones nuevas!",
  notificaciones_3: "sin leer",
  notificaciones_2: "notificación",
  notificaciones_1: "Tienes",
  notificaciones: "Notificaciones",
  error_marcar_notificacion: "Error al marcar la notificación",
  marcar_leida: "Marcar como leída",
  añadir_variables_globales: "Añadir variables globales",
  registra_variables_globales_de_producto:
    "Registra los valores globales que afectarán en los cálculos de los productos",
  set_añadir_variables: "Añadir variables",
  select_plataforma: "Selecciona plataforma",
  sin_plataformas_registradas: "No hay plataformas registradas",
  sin_variables_registradas: "No hay variables registradas",
  set_añadir_plataforma: "Añadir plataforma",
  plataforma_añadida_correctamente: "Plataforma añadida correctamente",
  plataforma_añadida_error: "Error al añadir la plataforma",
  variables_añadidas_correctamente: "Variables añadidas correctamente",
  variables_añadidas_error: "Error al añadir las variables",
  variables_actualizadas_correctamente: "Variables actualizadas correctamente",
  set_actualizar_variables: "Actualizar variables",
  general_actualizando: "Actualizando",
  sincronizar_ahora: "Sincronizar ahora",
  general_sincronizando: "Sincronizando",
  variables_sincronizadas_correctamente: "Productos sincronizados correctamente",
  variables_sincronizadas_error: "Error al sincronizar los productos",
  vista_previa: "Vista Previa",
  buscar_por_fecha: "Buscar por fecha",
  input_fecha: "Fecha",
  crear_orden_compra: "Crear orden de compra",
  sin_cambios_producto: "El producto no ha sido editado",
  set_actualizar_plataforma: "Actualizar plataforma",
  plataforma_actualizada_correctamente: "Plataforma actualizada correctamente",
  sin_productos_en_almacen: "Sin productos en almacen",
  canje_validado_correctamente: "Canje validado correctamente",
  canje_validado_error: "Error al validar el canje",
  asignar_proveedor: "Asignar un proveedor",
  general_asignando: "Asignando",
  set_asignar: "Asignar",
  proveedor_asignado_correctamente: "Proveedor asignado correctamente",
  proveedor_asignado_error: "Error al asignar el proveedor",
  general_registrando: "Registrando",
  set_registrar: "Registrar",
  nuevo_precio_registrado_correctamente: "Nuevo precio registrado correctamente",
  nuevo_precio_registrado_error: "Error al registrar el nuevo precio",
  validar_sin_proveedor: "Validar sin proveedor",
  registrar_nuevo_precio: "Registrar nuevo precio",
  input_precio_compra: "Precio de compra",
  registrar_mei_y_no_serie: "Registrar MEI y No. Serie",
  input_mei: "MEI",
  input_no_serie: "No. Serie",
  datos_registrados_correctamente: "Datos registrados correctamente",
};

export default textosMx;
